AdminKey = "ba5a5c16-840a-4a01-8817-3799d0492551"
JwtKey   = "981c5604-b982-482e-b6e9-6adbe8ea04ae"

MaxUnconfirmedUsersAge = "1ns"
MaxResetKeyAge         = "15m"

FromEmail = "dario.freire+fservices@gmail.com"

[ConfirmationEmail.en_US]
Subject = "Signup Confirmation"
Body = """
<p>Thank you for signing up!</p>
<p>Please confirm your account by opening the link:&nbsp;
<a href='http://example.com/confirm?l=en&ct={{.ConfirmationTokenStr}}'>CONFIRM ACCOUNT</a>
</p>
"""

[ConfirmationEmail.pt_PT]
Subject = "Confirmação de Registo"
Body = """
<p>Obrigado pelo seu registo!</p>
<p>Por favor confirme a sua conta abrindo o link:&nbsp;
<a href='http://example.com/confirm?l=en&ct={{.ConfirmationTokenStr}}'>CONFIRMAR REGISTO</a>
</p>
"""

[ResetPasswordEmail.en_US]
Subject = "Password Reset"
Body = """
<p>We have received a request to reset your password.</p>
<p>You can set a new password by opening the link:&nbsp;
<a href='http://example.com/reset-password?l=en&ct={{.ResetTokenStr}}'>RESET PASSWORD</a>
</p>
<p>If you don't want to change your password you can ignore this mail.</p>
"""

[ResetPasswordEmail.pt_PT]
Subject = "Alterar Password"
Body = """
<p>Recebemos um pedido para alterar a sua password.</p>
<p>Poderá escolher uma nova password abrindo o link:&nbsp;
<a href='http://example.com/reset-password?l=en&ct={{.ResetTokenStr}}'>ALTERAR PASSWORD</a>
</p>
<p>Se não quiser alterar a sua password, pode ignorar este email.</p>
"""
